name: pythonworkflow


on: 

  workflow_dispatch


jobs:

  data_pipeline:

    name: data_pipeline

    runs-on: ubuntu-latest

    steps:

      # Step 1: Set up Python 3.10

      - name: Set up Python 3.10

        uses: actions/setup-python@v2

        with:

          python-version: '3.10'

      

      # Step 2: Checkout code

      - name: Checkout code

        uses: actions/checkout@v4


      # Step 3: Clean data

      - name: clean_data

        run: |

          pwd

          ls -al

          cd ModelCleaning

          pip install pandas

          python cleandata.py

          ls -al


      # Step 4: Train and test model

      - name: train_test_dataset

        run: |

          pip install scikit-learn joblib

          python ModelCleaning/train_test_dataset.py

          ls -al
